# Generated by Django 6.1.1 on 2026-09-11 14:12
import uuid

from django.db import migrations


def populate_upload_keys(apps, schema_editor):
    Document = apps.get_model("documents", "Document")

    for document in Document.objects.filter(upload_key__isnull=True):
        document.upload_key = uuid.uuid4()
        document.save(update_fields=["upload_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_upload_key"),
    ]

    operations = [
        migrations.RunPython(
            populate_upload_keys,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
