# Generated by Django 6.1.1 on 2026-09-11 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_populate_upload_keys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='attachment',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='document',
            name='ticket_number',
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
